// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetroAchievCollection.Data;

#nullable disable

namespace RetroAchievCollection.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260425212309_Migration_1")]
    partial class Migration_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("RetroAchievCollection.Models.AchievementModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CodeIntegration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CodeIntegration")
                        .IsUnique();

                    b.HasIndex("GameId");

                    b.ToTable("achievements");
                });

            modelBuilder.Entity("RetroAchievCollection.Models.ConfigurationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("configuration");

                    b.HasData(
                        new
                        {
                            Id = new Guid("166117e9-2488-4e1a-98fc-f3ec4ca298aa"),
                            ApiKey = "",
                            UserName = ""
                        });
                });

            modelBuilder.Entity("RetroAchievCollection.Models.ConsoleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CodeIntegration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Company")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CodeIntegration")
                        .IsUnique();

                    b.ToTable("consoles");
                });

            modelBuilder.Entity("RetroAchievCollection.Models.GameModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CodeIntegration")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConsoleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Developer")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayCommand")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CodeIntegration")
                        .IsUnique();

                    b.HasIndex("ConsoleId");

                    b.ToTable("games");
                });

            modelBuilder.Entity("RetroAchievCollection.Models.AchievementModel", b =>
                {
                    b.HasOne("RetroAchievCollection.Models.GameModel", "GameModel")
                        .WithMany("Achievements")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameModel");
                });

            modelBuilder.Entity("RetroAchievCollection.Models.GameModel", b =>
                {
                    b.HasOne("RetroAchievCollection.Models.ConsoleModel", "ConsoleModel")
                        .WithMany()
                        .HasForeignKey("ConsoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsoleModel");
                });

            modelBuilder.Entity("RetroAchievCollection.Models.GameModel", b =>
                {
                    b.Navigation("Achievements");
                });
#pragma warning restore 612, 618
        }
    }
}
